services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: joaquimdb
      POSTGRES_PASSWORD: 221026
      POSTGRES_DB: nestdb
    ports:
      - '5433:5432'

